### ISSUE TITLE
imagenet_blnet_pretrained

### ISSUE THREAD

**Issue by ilkarman** [IBM/bLVNet-TAM#4]
Is it intentional to have 
```
if input_channels != 3
```
only in this [line](https://github.com/IBM/bLVNet-TAM/blob/master/core/models/blvnet_tam_backbone.py#L369)?

As it stands the code only loads the weights for the flow-case and not the RGB-case. I have thus extended the condition to the below and was wondering if it's correct:
```
        if input_channels != 3:  # flow
            ....
        else:
            print("Loading RGB weights")
            state_d = checkpoint['state_dict']
        model.load_state_dict(state_d, strict=False)
```

**Comment by chunfuchen** [comment]
@ilkarman, thanks for interesting in our codes. Yes, there is a bug to load rgb case, fixed ca70ba60fc8.
