### ISSUE TITLE
About Flow Training

### ISSUE THREAD

**Issue by hufengshuo07** [IBM/bLVNet-TAM#6]
I found that you haven't provide flow models, so if i want to retrain a flow model. 
Are all training parameters the same with RGB training? 
And do i need to train the model from scratch with random initialization?
Thanks~

**Comment by chunfuchen** [comment]
We train flow model with the same hyper-parameters used in RGB training.
For initialization, we use ImageNet's weights. For the first layer, we average the weights in the channel dimension and then repeat it to the number of channels of the flow model to avoid the inconsistent of the weights' shape.

**Comment by hufengshuo07** [comment]
Very helpful. Thanks.
